server: 
  port: 8001
spring:
  application: 
    name: rubick
  datasource:
    url: jdbc:mysql://localhost:3306/rubick?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rubick
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
#  redis:
#    port: 6379
#    database: 5
#    timeout: 1800000
#    pool:
#      maxIdle: 100
#      minIdle: 5
#      maxActive: 1000
#      maxWait: 3000
logging:
  file: /opt/logs/${spring.application.name}
  level:
    com.letsiot.eam: debug
    
SMS:
  ACCESSKEYID: LTAIj6lGxp9lILBn
  ACCESSKEYSECRET: 95KOIj1ad0U8z2CSppJ47M06YFcrP4
  SIGNNAME: 拉比克
  TEMPLET:
    FORGETPASSWORD: SMS_125016994
    WARN: SMS_139233533
  message: false