server: 
  port: 443
  ssl: 
    key-store: classpath:rubickjks.jks
    key-store-password: 2feztjV7
    key-store-type: JKS
    key-alias: alias
spring:
  application: 
    name: rubick
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/rubick?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: rubick
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
  http: 
    multipart: 
      maxFileSize: 10MB
      maxRequestSize: 10MB
logging:
  file: /opt/logs/${spring.application.name}
  level:
    com.letsiot.eam: debug
SMS:
  ACCESSKEYID: LTAIj6lGxp9lILBn
  ACCESSKEYSECRET: 95KOIj1ad0U8z2CSppJ47M06YFcrP4
  SIGNNAME: 拉比克
  TEMPLET:
    FORGETPASSWORD: SMS_125016994
    WARN: SMS_139233533
  message: false
file: 
  prefix: "/wx/images"
  prefixSecondSmall: "/small"
  prefixSecondBig: "/big"